image: cypress/browsers:node10.16.0-chrome77
lhci:
  script:
    - npm install -g npm
    - npm ci
    - ENV=production npm run build
    - ENV=production npm run export
    - npm install -g @lhci/cli@0.3.x
    - lhci autorun || echo “LHCI failed!”