[build]
  command   = "npm run build"
  functions = "out_functions"
  publish   = "out_publish"

[[plugins]]
package = "netlify-plugin-cache-nextjs"
package = "netlify-plugin-search-index"
  [plugins.inputs] =
    exclude = ['/thanks.html','/checkout.html']