// eslint-disable-next-line import/prefer-default-export
export const list = [
  {
    productName: 'The World Is Not Enough',
    slug: 'the-world-is-not-enough',
    description: "The World Is Not Enough&#160;is a&#160;first-person shooter&#160;based on&#160;MGM's 1999&#160;James Bond&#160;film of the same name, where the player assumes the role of&#160;James Bond&#160;through 11 different missions.",
    descriptionShort: "Experience the intensity of being the world's top secret agent. Equipped with a full arsenal of Q-Lab, you carry out action-packed missions based on the blockbuster movie.",
  },
  {
    productName: 'The Legend of Zelda: Ocarina of Time',
    slug: 'the-legend-of-zelda-ocarina-of-time',
    description: 'As a young boy, Link is tricked by Ganondorf, the King of the Gerudo Thieves. The evil human uses Link to gain access to the Sacred Realm, where he places his tainted hands on Triforce and transforms the beautiful Hyrulean landscape into a barren wasteland. Link is determined to fix the problems he helped to create, so with the help of Rauru he travels through time gathering the powers of the Seven Sages.',
    descriptionShort: 'Link travels through time gathering the powers of the Seven Sages to defeat Ganondorf.',
  },
  {
    productName: 'Riven: The Sequel to Myst',
    slug: 'riven-the-sequel-to-myst',
    description: '',
    descriptionShort: 'Enter a deceptively beautiful world torn apart by age-old conflicts...where secrets lie hidden at every turn...and nothing is as it seems.',
  },
  {
    productName: 'SimCity 2000',
    slug: 'simcity-2000',
    description: '',
    descriptionShort: 'Take on the role as a mayor and call the shots for the entire city. ',
  },
  {
    productName: 'The Neverhood',
    slug: 'the-neverhood',
    description: '',
    descriptionShort: 'Experience an unforgettable point and click adventure game with a unique style.',
  },
  {
    productName: 'Super Mario 64',
    slug: 'super-mario-64',
    description: "Mario is super in a whole new way! Combining the finest 3-D graphics ever developed for a video game and an explosive sound track, Super Mario 64 becomes a new standard for video games. It's packed with bruising battles, daunting obstacle courses and underwater adventures. Retrieve the Power Stars from their hidden locations and confront your arch nemesis - Bowser, King of the Koopas!",
    descriptionShort: 'Mario is super in a whole new way! ',
  },
  {
    productName: 'Tomb Raider IV: The Last Revelation',
    slug: 'tomb-raider-iv-the-last-revelation',
    description: '',
    descriptionShort: 'Lara Croft is in Egypt, minding her own business until a pool of quicksand pulls her underground, deep into an ancient tomb.',
  },
  {
    productName: 'Wing Commander 3',
    slug: 'wing-commander-3-heart-of-the-tiger',
    description: '',
    descriptionShort: 'You may be the hottest pilot in the fleet, but this will cool your jets!',
  },
  {
    productName: 'X-COM: Terror From the Deep',
    slug: 'x-com-terror-from-the-deep',
    description: 'X-COM: Terror from the Deep is the follow-up to the resource management and tactical combat game X-COM: Enemy Unknown.\n\nIt has been 40 years since X-COM last defeated the aliens. Now, in the year of 2040, aliens begin to appear on the Earth again. This time the threat to humanity is coming from the depths of oceans.\n\nThe game is almost identical to the original X-COM game. The user interface, weapons, and aliens are all the same. The only difference is the adaptation of the aliens and weapons (e.g. new hand-to-hand weapons) to the ocean environment. The game features both undersea and on-land missions, and is significantly harder than its predecessor.\n',
    descriptionShort: "Seeking to take advantage of a weakened Earth, X-COM's deep space foes unexpectedly change strategy and launch a powerful second front against planet Earth.",
  },
  {
    productName: "Tony Hawk's Pro Skater",
    slug: 'tony-hawks-pro-skater',
    description: '',
    descriptionShort: 'Skate as legendary Tony Hawk, or as one of nine top pros. Work your way up the ranks by landing suicidal tricks in brutal competitions to become the highest-ranked skate champ.',
  },
  {
    productName: 'Urban Chaos',
    slug: 'urban-chaos',
    description: '',
    descriptionShort: 'The new millennium approaches. Turmoil, crime, and famine rule. Gangs, terrorists and violent cults lurk around every corner.',
  },
  {
    productName: 'Worms Pinball',
    slug: 'worms-pinball',
    description: '',
    descriptionShort: 'The Worms crew returns, and this time theyve got balls!',
  },
  {
    productName: 'Super Mario Land',
    slug: 'super-mario-land',
    description: "Super Mario Land[a]&#160;is a 1989&#160;side-scrolling&#160;platform video game&#160;developed and published by&#160;Nintendo&#160;as a&#160;launch title&#160;for their&#160;Game Boy&#160;handheld game console. It is the first&#160;Mario&#160;platform game ever to be released for a handheld console. In gameplay similar to that of the 1985&#160;Super Mario Bros., but resized for the smaller device's screen, the player advances&#160;Mario&#160;to the end of 12&#160;levels&#160;by moving to the right and jumping across platforms to avoid enemies and pitfalls.",
    descriptionShort: 'Get Ready for a New Spin on a Familiar Tail. Super Mario Land reinvents everything fans love about Mario gaming!',
  },
  {
    productName: 'Worms Armageddon',
    slug: 'worms-armageddon',
    description: '',
    descriptionShort: 'Those intrepid invertebrates return with a vengeance in the much-loved Worms™ Armageddon. It’s a whole new can of worms! ',
  },
  {
    productName: 'X-COM: UFO Defense',
    slug: 'x-com-ufo-defense',
    description: '',
    descriptionShort: "You are in control of X-COM: an organization formed by the world's governments to fight the ever-increasing alien menace.",
  },
  {
    productName: 'Z: The Game',
    slug: 'z-1996',
    description: "Z is a real-time strategy game in which you fight for control of the sectors, some of which contains manufactories that can gain you additional units. Touch the \"flag\" in the sector and it's yours. Capture the sector before the new unit comes out of the manufactory and the new unit is yours. With six different robots (different armaments, armor, and speed), multiple vehicles (from jeeps to tanks) the robots can utilize, your ultimate objective is to destroy the opponent's base, and prevent him from doing the same to you.\n\nThe game differs from many other RTSs by emphasizing territorial control (and the manufactories) instead of getting kills and gathering a big army. You have to finely balance defense and offense. If you wait too long, the enemy will grab all the manufactories first. If you go too fast, you'll get hammered for stretching yourself too thin. You can hijack enemy vehicles by shooting the driver off. If you send a group of soldiers toward an objective and they find a vehicle, one of them will split off to grab the vehicle; you don't really need to micromanage each soldier.\n",
    descriptionShort: 'Under the command of General Zod, it is your job to take control of chain smoking, foul-mouthed, abusive, alcoholic robot-grunts.',
  },
  {
    productName: "Tony Hawk's Pro Skater 4",
    slug: 'tony-hawks-pro-skater-4',
    description: '',
    descriptionShort: "Build your skills, earn respect, and show that you've got what it takes to Go Pro. ",
  },
  {
    productName: 'Worms',
    slug: 'worms',
    description: '',
    descriptionShort: 'The worms are back in their most destructive game yet.',
  },
  {
    productName: 'Spyro: Year of the Dragon',
    slug: 'spyro-year-of-the-dragon',
    description: '',
    descriptionShort: 'Spyro the Dragon, and his best friend Sparx, face a journey into uncharted territory against his most fearsome enemy yet - the Sorceress!',
  },
  {
    productName: 'Star Wars Episode I: Racer',
    slug: 'star-wars-episode-i-racer',
    description: "Star Wars Episode I: Racer features a variety of tracks spanning several different planets. It also includes all of the racers featured in the movie as well as additional competitors exclusive to the game. The player character's&#160;podracer&#160;is equipped with a boost function that the player can activate. While activated the podracer's temperature will rise, and if the player boosts for too long, the engines will explode, destroying the podracer and costing the player several seconds as he/she&#160;respawns&#160;to continue racing. The podracer will also be destroyed if one or both engines sustain severe damage from colliding into too many walls or obstacles, requiring the player to steer carefully to avoid falling behind. The player can also actively repair the podracer while competing, however doing so results in a slower overall speed until repairs are either complete or stopped.</span>",
    descriptionShort: 'Star Wars Episode I: Racer features a variety of tracks spanning several different planets. It also includes all of the racers featured in the movie as well as additional competitors.',
  },
]
