// eslint-disable-next-line import/prefer-default-export
export const list = [
  {
    description: "It's a matter of laugh or death in Theme Hospital™, another installment of the Theme series. Design, maintain and manage a hi-tech hospital facility, making the most of limited resources and turning cures into cash. The Grim Reaper stalks the corridors, the ill have some very odd ailments, and the staff want to play doctors and nurses together. No matter how you look at it, you're in control of a very sick hospital.\n",
    descriptionShort: "It's a matter of laugh or death in Theme Hospital, another installment of the Theme series. Design, maintain and manage a hi-tech hospital facility and turning cures into cash. ",
    productName: 'Theme Hospital',
    publisher: '',
    slug: 'theme-hospital',
    studio: '',
    subname: '',
  },
  {
    description: "Mario is super in a whole new way! Combining the finest 3-D graphics ever developed for a video game and an explosive sound track, Super Mario 64 becomes a new standard for video games. It's packed with bruising battles, daunting obstacle courses and underwater adventures. Retrieve the Power Stars from their hidden locations and confront your arch nemesis - Bowser, King of the Koopas!",
    descriptionShort: 'Mario is super in a whole new way! Retrieve the Power Stars from their hidden locations and confront your arch nemesis - Bowser, King of the Koopas!',
    productName: 'Super Mario 64',
    publisher: 'Nintendo',
    slug: 'super-mario-64',
    studio: 'Nintendo',
    subname: '',
  },
  {
    description: '',
    descriptionShort: 'Spyro the Dragon, and his best friend Sparx, face a journey into uncharted territory against his most fearsome enemy yet - the Sorceress!',
    productName: 'Spyro',
    publisher: '',
    slug: 'spyro-year-of-the-dragon',
    studio: '',
    subname: 'Year of the Dragon',
  },
  {
    description: "Need for Speed: Porsche Unleashed tests your driving skills while you test-drive some of Porsche's most popular cars.",
    descriptionShort: "Need for Speed: Porsche Unleashed tests your driving skills while you test-drive some of Porsche's most popular cars.",
    productName: 'Need for Speed',
    publisher: '',
    slug: 'need-for-speed-porsche-unleashed',
    studio: '',
    subname: 'Porsche Unleashed',
  },
  {
    description: "Behind a veil of secrecy the evil Empire is creating a doomsday army - one that, if finished, will become the final cog in the Empire's arsenal of terror and domination.\nYour Mission? Join the Rebel Alliance's covert operations division, infiltrate the Empire, then battle every man and machine the Imperial Forces can muster. Search a vast galaxy for clues, attack enemy bases-all in a desperate attempt to stop the activation of this fearsome new weapon.",
    descriptionShort: "Join the Rebel Alliance's covert operations division, infiltrate the Empire, then battle every man and machine the Imperial Forces can muster.",
    productName: 'Star Wars',
    publisher: '',
    slug: 'star-wars-dark-forces',
    studio: '',
    subname: 'Dark Forces',
  },
  {
    description: "Star Wars Episode I: Racer features a variety of tracks spanning several different planets. It also includes all of the racers featured in the movie as well as additional competitors exclusive to the game. The player character's&#160;podracer&#160;is equipped with a boost function that the player can activate. While activated the podracer's temperature will rise, and if the player boosts for too long, the engines will explode, destroying the podracer and costing the player several seconds as he/she&#160;respawns&#160;to continue racing. The podracer will also be destroyed if one or both engines sustain severe damage from colliding into too many walls or obstacles, requiring the player to steer carefully to avoid falling behind. The player can also actively repair the podracer while competing, however doing so results in a slower overall speed until repairs are either complete or stopped.</span>",
    descriptionShort: 'Climb on, strap in, and experience the pure adrenaline-pumping excitement of the Podracing sequence from Star Wars: Episode I.',
    productName: 'Star Wars',
    publisher: '',
    slug: 'star-wars-episode-i-racer',
    studio: '',
    subname: 'Episode I: Racer',
  },
  {
    description: "Thousands of years ago a meteor crashed into Antarctica and the shockwaves of its impact are being felt in the modern age. Lara Croft will follow clues leading to a deadly secret, boldly leaping chasms and blasting monsters that no one has leaped or blasted before. This time she faces a mystery that's from way out of this world. Tomb Raider III is a complex adventure that combines puzzles with high-speed action.",
    descriptionShort: 'Lara Croft follows clues leading to a deadly secret, boldly leaping chasms and blasting monsters that no one has leaped or blasted before.',
    productName: 'Tomb Raider 3',
    publisher: '',
    slug: 'tomb-raider-3-adventures-of-lara-croft',
    studio: '',
    subname: 'Adventures of Lara Croft',
  },
  {
    description: '',
    descriptionShort: "You are in control of X-COM: an organization formed by the world's governments to fight the ever-increasing alien menace.",
    productName: 'X-COM',
    publisher: '',
    slug: 'x-com-ufo-defense',
    studio: '',
    subname: 'UFO Defense',
  },
  {
    description: 'X-COM: Terror from the Deep is the follow-up to the resource management and tactical combat game X-COM: Enemy Unknown.\n\nIt has been 40 years since X-COM last defeated the aliens. Now, in the year of 2040, aliens begin to appear on the Earth again. This time the threat to humanity is coming from the depths of oceans.\n\nThe game is almost identical to the original X-COM game. The user interface, weapons, and aliens are all the same. The only difference is the adaptation of the aliens and weapons (e.g. new hand-to-hand weapons) to the ocean environment. The game features both undersea and on-land missions, and is significantly harder than its predecessor.\n',
    descriptionShort: "Seeking to take advantage of a weakened Earth, X-COM's deep space foes unexpectedly change strategy and launch a powerful second front against planet Earth.",
    productName: 'X-COM',
    publisher: '',
    slug: 'x-com-terror-from-the-deep',
    studio: '',
    subname: 'Terror From the Deep',
  },
  {
    description: '',
    descriptionShort: 'Lara Croft is in Egypt, minding her own business until a pool of quicksand pulls her underground, deep into an ancient tomb.',
    productName: 'Tomb Raider IV',
    publisher: '',
    slug: 'tomb-raider-iv-the-last-revelation',
    studio: '',
    subname: 'The Last Revelation',
  },
  {
    description: '',
    descriptionShort: 'Enter a deceptively beautiful world torn apart by age-old conflicts...where secrets lie hidden at every turn...and nothing is as it seems.',
    productName: 'Riven',
    publisher: '',
    slug: 'riven-the-sequel-to-myst',
    studio: '',
    subname: 'The Sequel to Myst',
  },
  {
    description: 'As a young boy, Link is tricked by Ganondorf, the King of the Gerudo Thieves. The evil human uses Link to gain access to the Sacred Realm, where he places his tainted hands on Triforce and transforms the beautiful Hyrulean landscape into a barren wasteland. Link is determined to fix the problems he helped to create, so with the help of Rauru he travels through time gathering the powers of the Seven Sages.',
    descriptionShort: 'Link travels through time gathering the powers of the Seven Sages to defeat Ganondorf.',
    productName: 'The Legend of Zelda',
    publisher: '',
    slug: 'the-legend-of-zelda-ocarina-of-time',
    studio: '',
    subname: 'Ocarina of Time',
  },
  {
    description: "The World Is Not Enough&#160;is a&#160;first-person shooter&#160;based on&#160;MGM's 1999&#160;James Bond&#160;film of the same name, where the player assumes the role of&#160;James Bond&#160;through 11 different missions.",
    descriptionShort: "Experience the intensity of being the world's top secret agent. Equipped with a full arsenal of Q-Lab, you carry out action-packed missions based on the blockbuster movie.",
    productName: '007',
    publisher: '',
    slug: 'the-world-is-not-enough',
    studio: '',
    subname: 'The World Is Not Enough',
  },
  {
    description: '',
    descriptionShort: 'Take on the role as a mayor and call the shots for the entire city. ',
    productName: 'SimCity 2000',
    publisher: '',
    slug: 'simcity-2000',
    studio: '',
    subname: '',
  },
  {
    description: '',
    descriptionShort: 'Experience an unforgettable point and click adventure game with a unique style.',
    productName: 'The Neverhood',
    publisher: '',
    slug: 'the-neverhood',
    studio: '',
    subname: '',
  },
  {
    description: '',
    descriptionShort: 'You may be the hottest pilot in the fleet, but this will cool your jets!',
    productName: 'Wing Commander 3',
    publisher: '',
    slug: 'wing-commander-3-heart-of-the-tiger',
    studio: '',
    subname: '',
  },
  {
    description: '',
    descriptionShort: 'Skate as legendary Tony Hawk, or as one of nine top pros. Work your way up the ranks by landing suicidal tricks in brutal competitions to become the highest-ranked skate champ.',
    productName: "Tony Hawk's Pro Skater",
    publisher: '',
    slug: 'tony-hawks-pro-skater',
    studio: '',
    subname: '',
  },
  {
    description: '',
    descriptionShort: 'The new millennium approaches. Turmoil, crime, and famine rule. Gangs, terrorists and violent cults lurk around every corner.',
    productName: 'Urban Chaos',
    publisher: '',
    slug: 'urban-chaos',
    studio: '',
    subname: '',
  },
  {
    description: '',
    descriptionShort: 'The Worms crew returns, and this time theyve got balls!',
    productName: 'Worms Pinball',
    publisher: '',
    slug: 'worms-pinball',
    studio: '',
    subname: '',
  },
  {
    description: "Super Mario Land[a]&#160;is a 1989&#160;side-scrolling&#160;platform video game&#160;developed and published by&#160;Nintendo&#160;as a&#160;launch title&#160;for their&#160;Game Boy&#160;handheld game console. It is the first&#160;Mario&#160;platform game ever to be released for a handheld console. In gameplay similar to that of the 1985&#160;Super Mario Bros., but resized for the smaller device's screen, the player advances&#160;Mario&#160;to the end of 12&#160;levels&#160;by moving to the right and jumping across platforms to avoid enemies and pitfalls.",
    descriptionShort: 'Get Ready for a New Spin on a Familiar Tail. Super Mario Land reinvents everything fans love about Mario gaming!',
    productName: 'Super Mario Land',
    publisher: '',
    slug: 'super-mario-land',
    studio: '',
    subname: '',
  },
]
